/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/ActionBarManager")]
    [LuaRegisterType(0x5860b0cdbf1d169f, typeof(LuaBehaviour))]
    public class ActionBarManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "84d880a67304f494a89e0dfa3d2a532e";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("0693918c8aa324541bca72d24e4a7002")]
        [SerializeField] public UnityEngine.Object m_actionBarUI = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_actionBarUI),
            };
        }
    }
}

#endif
