/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CullOnEnter")]
    [LuaRegisterType(0xf5ec543c2701ff4a, typeof(LuaBehaviour))]
    public class CullOnEnter : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "f5f6441ad96dfdd4ba13c39de9bf0f1d";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Collections.Generic.List<UnityEngine.GameObject> m_cullObjects = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_cullObjects),
            };
        }
    }
}

#endif
