/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/Decoration")]
    [LuaRegisterType(0xef01c03299bbb83, typeof(LuaBehaviour))]
    public class Decoration : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "6c79ec1af1bf4b44193b1d0ada14ba5b";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double m_decorationId = 0;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_decorationId),
            };
        }
    }
}

#endif
