/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/DecorationsModule")]
    [LuaRegisterType(0x9ac4d6c119aaf7b8, typeof(LuaBehaviour))]
    public class DecorationsModule : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "55dac512d4a812c46a273844782eaa3b";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Collections.Generic.List<UnityEngine.GameObject> m_decorationModels = default;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Texture> m_decorationIcons = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_decorationModels),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_decorationIcons),
            };
        }
    }
}

#endif
