/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/DecorationTile")]
    [LuaRegisterType(0xb576ab6890f89977, typeof(LuaBehaviour))]
    public class DecorationTile : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "b3ec617ad4540334f92ebe709aca7261";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Vector2 m_pos = new Vector2(0f, 0f);
        [SerializeField] public UnityEngine.Material m_availableMaterial = default;
        [SerializeField] public UnityEngine.Material m_occupiedMaterial = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_pos),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_availableMaterial),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_occupiedMaterial),
            };
        }
    }
}

#endif
