/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/DiggingPoints")]
    [LuaRegisterType(0xe374178c58569dbb, typeof(LuaBehaviour))]
    public class DiggingPoints : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "066f2991ccd93874aaa3c3c5fe3e2ebe";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double m_tier = 0;
        [SerializeField] public System.Double m_targetActivePoints = 0;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_tier),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_targetActivePoints),
            };
        }
    }
}

#endif
