/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/EditShop")]
    [LuaRegisterType(0xa7463078d0eb935d, typeof(LuaBehaviour))]
    public class EditShop : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "00f3fed9fd66c4340a5a5677124c1c48";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("3de5b2981b284b4488f9f3928c048d91")]
        [SerializeField] public UnityEngine.Object m_shopScript = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_shopScript),
            };
        }
    }
}

#endif
