/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/ItemsBuy")]
    [LuaRegisterType(0x7af69c125c6ac8cd, typeof(LuaBehaviour))]
    public class ItemsBuy : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "fcc2a138888a0ee4dacae489e02c8d04";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_shopType = "";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_shopType),
            };
        }
    }
}

#endif
