/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/IWP_UI")]
    [LuaRegisterType(0x505fbbd28c8c3916, typeof(LuaBehaviour))]
    public class IWP_UI : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "0c19239094026ac4f8c37f5cee91c7fe";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Texture m_closeIcon = default;
        [SerializeField] public UnityEngine.Texture m_coinIcon = default;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Texture> m_iwpIcons = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_closeIcon),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_coinIcon),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
                CreateSerializedProperty(_script.GetPropertyAt(3), null),
                CreateSerializedProperty(_script.GetPropertyAt(4), null),
                CreateSerializedProperty(_script.GetPropertyAt(5), null),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_iwpIcons),
            };
        }
    }
}

#endif
