/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/NameTag_UI")]
    [LuaRegisterType(0xd14932e4b5dd0e49, typeof(LuaBehaviour))]
    public class NameTag_UI : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "a593ef50f1f7b5c43b09245927e1b0fc";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_nameText = "";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), null),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_nameText),
            };
        }
    }
}

#endif
