/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/Shop")]
    [LuaRegisterType(0x716a5f24e3fe97e9, typeof(LuaBehaviour))]
    public class Shop : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "3de5b2981b284b4488f9f3928c048d91";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double m_shopId = 0;
        [SerializeField] public UnityEngine.Transform m_tablesParent = default;
        [SerializeField] public UnityEngine.GameObject m_playerIndicator = default;
        [LuaScriptPropertyAttribute("00f3fed9fd66c4340a5a5677124c1c48")]
        [SerializeField] public UnityEngine.Object m_editShopScript = default;
        [LuaScriptPropertyAttribute("a593ef50f1f7b5c43b09245927e1b0fc")]
        [SerializeField] public UnityEngine.Object m_nameTag = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_shopId),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_tablesParent),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_playerIndicator),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_editShopScript),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_nameTag),
            };
        }
    }
}

#endif
