/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/SineAnimation")]
    [LuaRegisterType(0x6dc9a3e10cf3fb6, typeof(LuaBehaviour))]
    public class SineAnimation : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "30a0db25e1301a04c8dc50d8e285f773";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Transform m_targetTransform = default;
        [SerializeField] public System.Double m_speed = 1;
        [SerializeField] public System.Boolean m_randomTimeOffset = true;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_targetTransform),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_speed),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_randomTimeOffset),
            };
        }
    }
}

#endif
