/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/Teleport")]
    [LuaRegisterType(0x5fcca28d2423539e, typeof(LuaBehaviour))]
    public class Teleport : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "966205e6a8cf11648849375bf9a63a2c";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Transform m_destination = default;
        [SerializeField] public UnityEngine.GameObject m_teleportParticles = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_destination),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_teleportParticles),
            };
        }
    }
}

#endif
