/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/Teleporter")]
    [LuaRegisterType(0x206aebecc516c5e9, typeof(LuaBehaviour))]
    public class Teleporter : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "9fb8d849b2bbd434c85e0e1bf2e345d4";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Transform m_destination = default;
        [Tooltip("Whether to play a sound when using the teleporter, local player only")]
        [SerializeField] public System.Boolean m_playSound = false;
        [Tooltip("The audio shader to play when teleporting.")]
        [SerializeField] public Highrise.AudioShader m_soundToPlay = default;
        [Tooltip("Whether to play a particle effect when using the teleporter.")]
        [SerializeField] public System.Boolean m_playParticleEffect = true;
        [Tooltip("The prefab containing the particle effect to play at the destination after teleporting")]
        [SerializeField] public UnityEngine.GameObject m_teleportParticles = default;
        [Tooltip("If false, the character will immediately teleport when entering the trigger, otherwise adds a button to the action bar to teleport.")]
        [SerializeField] public System.Boolean m_useActionBar = true;
        [SerializeField] public UnityEngine.Texture2D m_icon = default;
        [SerializeField] public System.Double m_sorting = 0;
        [Tooltip("Whether to move the camera to your character after teleporting.")]
        [SerializeField] public System.Boolean m_resetCameraAfterTeleport = true;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_destination),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_playSound),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_soundToPlay),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_playParticleEffect),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_teleportParticles),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_useActionBar),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_icon),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_sorting),
                CreateSerializedProperty(_script.GetPropertyAt(8), m_resetCameraAfterTeleport),
            };
        }
    }
}

#endif
