/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/Toy")]
    [LuaRegisterType(0x6d02e519e21ec3e7, typeof(LuaBehaviour))]
    public class Toy : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "cf8d19345c2c60e4c8e458fe054ebd2e";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Collections.Generic.List<UnityEngine.AudioClip> m_diggingSounds = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_diggingSounds),
            };
        }
    }
}

#endif
