/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/ToyCollected_UI")]
    [LuaRegisterType(0xc92d085dc4800efd, typeof(LuaBehaviour))]
    public class ToyCollected_UI : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "26113b828d1db2c44ad21ccd3812bb10";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double m_showTime = 0;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), null),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_showTime),
            };
        }
    }
}

#endif
