/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/ToysModule")]
    [LuaRegisterType(0xfd6babc2c788374, typeof(LuaBehaviour))]
    public class ToysModule : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "69060de8d0b3a1c4c833a48b90e45362";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Collections.Generic.List<UnityEngine.GameObject> m_toyModels = default;
        [SerializeField] public System.Collections.Generic.List<System.Double> m_toyPrices = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_toyModels),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_toyPrices),
            };
        }
    }
}

#endif
