/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/TrueBillboarding")]
    [LuaRegisterType(0xbdc431f53db96214, typeof(LuaBehaviour))]
    public class TrueBillboarding : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "78b0c5c253c5ec2408d9ddf2a07fc4d3";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("The distance the rig should offset toward the camera to account for clipping")]
        [SerializeField] public System.Double m_rigOffset = 0.75;
        [Tooltip("The maximum pitch angle for the character rig")]
        [SerializeField] public System.Double m_xRotationClamp = 30;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_rigOffset),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_xRotationClamp),
            };
        }
    }
}

#endif
