/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/Tutorial_UI")]
    [LuaRegisterType(0x2167fbbe16ab4e2, typeof(LuaBehaviour))]
    public class Tutorial_UI : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "5048b09a707222d429a8533888707e1d";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Texture m_closeIcon = default;
        [SerializeField] public UnityEngine.Texture m_nextIcon = default;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Texture> m_tutorialImages = default;
        [SerializeField] public System.Collections.Generic.List<System.String> m_tutorialDescriptions = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_closeIcon),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_nextIcon),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_tutorialImages),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_tutorialDescriptions),
                CreateSerializedProperty(_script.GetPropertyAt(4), null),
                CreateSerializedProperty(_script.GetPropertyAt(5), null),
                CreateSerializedProperty(_script.GetPropertyAt(6), null),
                CreateSerializedProperty(_script.GetPropertyAt(7), null),
                CreateSerializedProperty(_script.GetPropertyAt(8), null),
                CreateSerializedProperty(_script.GetPropertyAt(9), null),
                CreateSerializedProperty(_script.GetPropertyAt(10), null),
            };
        }
    }
}

#endif
