/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UIManagerModule")]
    [LuaRegisterType(0xe3be2f8eee762c6, typeof(LuaBehaviour))]
    public class UIManagerModule : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "230694961ba5d794480061662f7f5bdb";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("ce6d7af3415efa440be9f37545cc3f2b")]
        [SerializeField] public UnityEngine.Object m_leftHUD = default;
        [LuaScriptPropertyAttribute("cc0a8412b0339ed4a90a8bcd7f19bbc8")]
        [SerializeField] public UnityEngine.Object m_shopUI = default;
        [LuaScriptPropertyAttribute("c954854e52d04b1408265e21bee69c94")]
        [SerializeField] public UnityEngine.Object m_bridgePopUpUI = default;
        [LuaScriptPropertyAttribute("cc2d86f5e3aeed041b46c799b231e707")]
        [SerializeField] public UnityEngine.Object m_upgradesUI = default;
        [LuaScriptPropertyAttribute("5048b09a707222d429a8533888707e1d")]
        [SerializeField] public UnityEngine.Object m_tutorialUI = default;
        [LuaScriptPropertyAttribute("26113b828d1db2c44ad21ccd3812bb10")]
        [SerializeField] public UnityEngine.Object m_toyCollectedUI = default;
        [LuaScriptPropertyAttribute("8cde22022d1f44b4b81091cce10161d9")]
        [SerializeField] public UnityEngine.Object m_itemsShopUI = default;
        [LuaScriptPropertyAttribute("a9b8ea38ce8c83b4eba8e6f4736bc3d5")]
        [SerializeField] public UnityEngine.Object m_editShopButtonUI = default;
        [LuaScriptPropertyAttribute("1cd0e2608667baa4ab31d6cbaeb1973f")]
        [SerializeField] public UnityEngine.Object m_editShopUI = default;
        [LuaScriptPropertyAttribute("be0fc91170a97b546b20ecd1e9e57e15")]
        [SerializeField] public UnityEngine.Object m_ownedDecorationsUI = default;
        [LuaScriptPropertyAttribute("7fc55d8bfe6711f44a06a6abc1eb8468")]
        [SerializeField] public UnityEngine.Object m_placeDecorationUI = default;
        [LuaScriptPropertyAttribute("2e936b0e40ecfe440a09d8495a2e1c39")]
        [SerializeField] public UnityEngine.Object m_removeDecorationsUI = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_leftHUD),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_shopUI),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_bridgePopUpUI),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_upgradesUI),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_tutorialUI),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_toyCollectedUI),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_itemsShopUI),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_editShopButtonUI),
                CreateSerializedProperty(_script.GetPropertyAt(8), m_editShopUI),
                CreateSerializedProperty(_script.GetPropertyAt(9), m_ownedDecorationsUI),
                CreateSerializedProperty(_script.GetPropertyAt(10), m_placeDecorationUI),
                CreateSerializedProperty(_script.GetPropertyAt(11), m_removeDecorationsUI),
            };
        }
    }
}

#endif
