/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UIManagerModule")]
    [LuaRegisterType(0xe3be2f8eee762c6, typeof(LuaBehaviour))]
    public class UIManagerModule : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "230694961ba5d794480061662f7f5bdb";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("ce6d7af3415efa440be9f37545cc3f2b")]
        [SerializeField] public UnityEngine.Object m_leftHUD = default;
        [LuaScriptPropertyAttribute("cc0a8412b0339ed4a90a8bcd7f19bbc8")]
        [SerializeField] public UnityEngine.Object m_shopUI = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_leftHUD),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_shopUI),
            };
        }
    }
}

#endif
