/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/WaterAnimation")]
    [LuaRegisterType(0xb657dea063fbda5e, typeof(LuaBehaviour))]
    public class WaterAnimation : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "322c0a3970ad9c44d932c8725e33f4da";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Transform m_targetTransform = default;
        [SerializeField] public System.Double m_speed = 1;
        [SerializeField] public System.Double m_amplitude = 1;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_targetTransform),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_speed),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_amplitude),
            };
        }
    }
}

#endif
